name: grocery_plus
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  built_value: ^8.9.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  storage_database: ^2.0.5
  uuid: ^4.5.1
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
   # Add this as well


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

 
  assets:
   - images/
  